"""update companies table

Revision ID: 85599fb46b3d
Revises: 8203b49951e0
Create Date: 2026-01-30 16:11:33.960792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85599fb46b3d'
down_revision: Union[str, Sequence[str], None] = '8203b49951e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('companies_user_id_key'), 'companies', type_='unique')
    op.drop_column('companies', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('companies_user_id_key'), 'companies', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
